### ISSUE TITLE
plz add to crates.io

### ISSUE THREAD

**Issue by whoizit** [lbonn/i3-focus-last#1]
for easy installation

**Comment by lbonn** [comment]
Good idea :+1:!

Here it is: https://crates.io/crates/i3-focus-last

**Comment by whoizit** [comment]
can u please update?

**Comment by lbonn** [comment]
Ok I'll publish v0.4.0 with the switch from gumdrop and the new api to get the full focus list from the daemon.

I'm using the menu-plus branch on my machine which adds a menu tool (like rofi's window mode) but it still needs a fork of i3ipc-rs with some unmerged additions. So it can't really be published on crates.io right now.

Why do you ask actually? Are you interested in the new features or just like to have something up to date?

**Comment by whoizit** [comment]
I just thought you'd forgotten or too lazy to update
