### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by whoizit** [lbonn/i3-focus-last#4]
I periodically get crash with information about i3-focus-last.
```
$ rustc -V
rustc 1.47.0
```
![IMG_20201026_224440](https://user-images.githubusercontent.com/359276/97287465-aa193e80-1855-11eb-838e-11879c29a3d7.jpg)

**Comment by lbonn** [comment]
Seems related: https://github.com/JayceFayne/swayipc-rs/issues/26

**Comment by whoizit** [comment]
doesn't happen anymore
