### ISSUE TITLE
If target window would be hidden by a different full screen window, "un-fullscreen" that window

### ISSUE THREAD

**Issue by markstos** [lbonn/i3-focus-last#5]
## To reproduce with Sway 1.5.1:

  1. Open windows A and B on a workspace
  2. Fullscreen window A
  3. Launch `i3-focus-last menu` and select B

## Expected Result

Window "B" becomes visible and focused

## Current behavior

Nothing visibly happens-- Window A remains fullscreen, hiding window B.

**Comment by lbonn** [comment]
I've just tested on i3 and it behaves as you expect out of the box. We probably have to report the issue to sway.

**Comment by lbonn** [comment]
Fixed upstream.

**Comment by markstos** [comment]
The first release with the fix should be Sway 1.6.
